In [1]:
import pandas as pd
df=pd.read_excel('Dataset.xlsx')
df.head()

,ANC,LATITUDE,BLOCK,offensegroup,location,sector,YBLOCK,METHOD,CCN,END_DATE,...,DISTRICT,XBLOCK,YEAR,REPORT_DAT,ucr-rank,offensekey,START_DATE,VOTING_PRECINCT,OFFENSE,BLOCK_GROUP
0,6E,38.903732,100 - 199 block of l street ne,property,"38.9037316022,-77.0047283051",5D1,137319.550000,others,25002077,NaN,...,5.0,399589.870000,2025,"1/4/2025, 10:13:33 PM",6,property|theft/other,"1/4/2025, 9:24:00 PM",precinct 144,theft/other,010603 3
1,2C,38.903743,18th street nw and l street nw,property,"38.9037432394,-77.0416730027",2D3,137321.656253,others,25008226,NaN,...,2.0,396385.312507,2025,"1/18/2025, 4:03:46 AM",7,property|theft f/auto,"1/18/2025, 3:15:00 AM",precinct 17,theft f/auto,010700 1
2,1B,38.917236,2000 - 2099 block of 8th street nw,property,"38.917236462,-77.0229457261",3D2,138818.940000,others,25013256,"1/28/2025, 12:50:00 PM",...,3.0,398010.080000,2025,"1/28/2025, 1:14:31 PM",6,property|theft/other,"1/28/2025, 12:21:00 PM",precinct 37,theft/other,003500 3
3,5D,38.909405,1300 - 1399 block of 5th street ne,property,"38.9094049494,-76.9975459006",5D1,137949.330000,others,25001526,"1/3/2025, 9:14:00 PM",...,5.0,400212.850000,2025,"1/3/2025, 9:14:02 PM",8,property|motor vehicle theft,"1/3/2025, 8:40:00 PM",precinct 76,motor vehicle theft,008803 2
4,1D,38.930801,1600 - 1665 block of lamont street nw,property,"38.9308014266,-77.0373827045",3D1,140325.180000,others,25002498,"1/3/2025, 10:00:00 AM",...,3.0,396758.680000,2025,"1/6/2025, 12:50:14 AM",6,property|theft/other,"1/2/2025, 10:00:00 PM",precinct 40,theft/other,002702 1

In [2]:
print(df.columns)

Index(['ANC', 'LATITUDE', 'BLOCK', 'offensegroup', 'location', 'sector',
       'YBLOCK', 'METHOD', 'CCN', 'END_DATE', 'LONGITUDE', 'offense-text',
       'NEIGHBORHOOD_CLUSTER', 'SHIFT', 'PSA', 'CENSUS_TRACT', 'WARD', 'BID',
       'OCTO_RECORD_ID', 'DISTRICT', 'XBLOCK', 'YEAR', 'REPORT_DAT',
       'ucr-rank', 'offensekey', 'START_DATE', 'VOTING_PRECINCT', 'OFFENSE',
       'BLOCK_GROUP'],
      dtype='object')

In [3]:
df.dtypes

ANC                      object
LATITUDE                float64
BLOCK                    object
offensegroup             object
location                 object
sector                   object
YBLOCK                  float64
METHOD                   object
CCN                       int64
END_DATE                 object
LONGITUDE               float64
offense-text             object
NEIGHBORHOOD_CLUSTER     object
SHIFT                    object
PSA                     float64
CENSUS_TRACT            float64
WARD                    float64
BID                      object
OCTO_RECORD_ID          float64
DISTRICT                float64
XBLOCK                  float64
YEAR                      int64
REPORT_DAT               object
ucr-rank                  int64
offensekey               object
START_DATE               object
VOTING_PRECINCT          object
OFFENSE                  object
BLOCK_GROUP              object
dtype: object

In [4]:
df.isna().sum()

ANC                        1
LATITUDE                   0
BLOCK                      0
offensegroup               0
location                   0
sector                     8
YBLOCK                     0
METHOD                     0
CCN                        0
END_DATE                 284
LONGITUDE                  0
offense-text               0
NEIGHBORHOOD_CLUSTER       1
SHIFT                      0
PSA                        8
CENSUS_TRACT               4
WARD                       1
BID                     3181
OCTO_RECORD_ID          3867
DISTRICT                   8
XBLOCK                     0
YEAR                       0
REPORT_DAT                 0
ucr-rank                   0
offensekey                 0
START_DATE                 1
VOTING_PRECINCT            1
OFFENSE                    0
BLOCK_GROUP                4
dtype: int64

In [5]:
df['END_DATE']=pd.to_datetime(df['END_DATE'])
df['REPORT_DAT']=pd.to_datetime(df['REPORT_DAT'])
df['START_DATE']=pd.to_datetime(df['START_DATE'])
df.dtypes

C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\45176835.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['REPORT_DAT']=pd.to_datetime(df['REPORT_DAT'])
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\45176835.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['START_DATE']=pd.to_datetime(df['START_DATE'])

ANC                             object
LATITUDE                       float64
BLOCK                           object
offensegroup                    object
location                        object
sector                          object
YBLOCK                         float64
METHOD                          object
CCN                              int64
END_DATE                datetime64[ns]
LONGITUDE                      float64
offense-text                    object
NEIGHBORHOOD_CLUSTER            object
SHIFT                           object
PSA                            float64
CENSUS_TRACT                   float64
WARD                           float64
BID                             object
OCTO_RECORD_ID                 float64
DISTRICT                       float64
XBLOCK                         float64
YEAR                             int64
REPORT_DAT              datetime64[ns]
ucr-rank                         int64
offensekey                      object
START_DATE              datetime64[ns]
VOTING_PRECINCT                 object
OFFENSE                         object
BLOCK_GROUP                     object
dtype: object

In [6]:
df.isna().sum()

ANC                        1
LATITUDE                   0
BLOCK                      0
offensegroup               0
location                   0
sector                     8
YBLOCK                     0
METHOD                     0
CCN                        0
END_DATE                 284
LONGITUDE                  0
offense-text               0
NEIGHBORHOOD_CLUSTER       1
SHIFT                      0
PSA                        8
CENSUS_TRACT               4
WARD                       1
BID                     3181
OCTO_RECORD_ID          3867
DISTRICT                   8
XBLOCK                     0
YEAR                       0
REPORT_DAT                 0
ucr-rank                   0
offensekey                 0
START_DATE                 1
VOTING_PRECINCT            1
OFFENSE                    0
BLOCK_GROUP                4
dtype: int64

In [7]:
df.drop(columns=['OCTO_RECORD_ID','BID'],inplace=True)
df.isna().sum()

ANC                       1
LATITUDE                  0
BLOCK                     0
offensegroup              0
location                  0
sector                    8
YBLOCK                    0
METHOD                    0
CCN                       0
END_DATE                284
LONGITUDE                 0
offense-text              0
NEIGHBORHOOD_CLUSTER      1
SHIFT                     0
PSA                       8
CENSUS_TRACT              4
WARD                      1
DISTRICT                  8
XBLOCK                    0
YEAR                      0
REPORT_DAT                0
ucr-rank                  0
offensekey                0
START_DATE                1
VOTING_PRECINCT           1
OFFENSE                   0
BLOCK_GROUP               4
dtype: int64

In [8]:
df['ANC'].fillna(df['ANC'].mode()[0],inplace=True)
df.isna().sum()

C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\2884889841.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ANC'].fillna(df['ANC'].mode()[0],inplace=True)

ANC                       0
LATITUDE                  0
BLOCK                     0
offensegroup              0
location                  0
sector                    8
YBLOCK                    0
METHOD                    0
CCN                       0
END_DATE                284
LONGITUDE                 0
offense-text              0
NEIGHBORHOOD_CLUSTER      1
SHIFT                     0
PSA                       8
CENSUS_TRACT              4
WARD                      1
DISTRICT                  8
XBLOCK                    0
YEAR                      0
REPORT_DAT                0
ucr-rank                  0
offensekey                0
START_DATE                1
VOTING_PRECINCT           1
OFFENSE                   0
BLOCK_GROUP               4
dtype: int64

In [9]:
df['WARD'].fillna(df['WARD'].mode()[0],inplace=True)
df['VOTING_PRECINCT'].fillna(df['VOTING_PRECINCT'].mode()[0],inplace=True)
df['NEIGHBORHOOD_CLUSTER'].fillna('Unknown',inplace=True)
df['BLOCK_GROUP'].fillna('Unknown',inplace=True)
df['DISTRICT'].fillna('Unknown',inplace=True)
df['CENSUS_TRACT'].fillna('Unknown',inplace=True)
df['PSA'].fillna('Unknown',inplace=True)
df['sector'].fillna('Unknown',inplace=True)
df.isna().sum()

C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['WARD'].fillna(df['WARD'].mode()[0],inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['VOTING_PRECINCT'].fillna(df['VOTING_PRECINCT'].mode()[0],inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['NEIGHBORHOOD_CLUSTER'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BLOCK_GROUP'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DISTRICT'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['DISTRICT'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CENSUS_TRACT'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['CENSUS_TRACT'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PSA'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['PSA'].fillna('Unknown',inplace=True)
C:\Users\ishaa\AppData\Local\Temp\ipykernel_7924\1962741249.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sector'].fillna('Unknown',inplace=True)

ANC                       0
LATITUDE                  0
BLOCK                     0
offensegroup              0
location                  0
sector                    0
YBLOCK                    0
METHOD                    0
CCN                       0
END_DATE                284
LONGITUDE                 0
offense-text              0
NEIGHBORHOOD_CLUSTER      0
SHIFT                     0
PSA                       0
CENSUS_TRACT              0
WARD                      0
DISTRICT                  0
XBLOCK                    0
YEAR                      0
REPORT_DAT                0
ucr-rank                  0
offensekey                0
START_DATE                1
VOTING_PRECINCT           0
OFFENSE                   0
BLOCK_GROUP               0
dtype: int64

In [10]:
df.to_csv('Working dataset.csv',index=False)